### ISSUE TITLE
Doc tests are not compiling

### ISSUE THREAD

**Issue by yara-blue** [chronicl/typed-sled#5]
Right now all the doc tests are not compiling. The examples provided in the documentation while correct in spirit can not compile. Mostly there are missing type declarations and some missing `;`.

Normally I would not bring this up however since this lib has been published I think the documentation should be spot on.

**Comment by chronicl** [comment]
Thank you for the feedback and the pull requests!

I'll update this soon.

**Comment by yara-blue** [comment]
Take your time and again thanks for the lib. This was exactly what I was looking for.
