### ISSUE TITLE
Transaction for tuple of trees

### ISSUE THREAD

**Issue by ZettaScript** [chronicl/typed-sled#8]
Sled allows transactions for tuples of trees. It would be nice that typed-sled allows it too, as it enables atomic transactions on multiple trees.

I started [an implementation in a fork](https://github.com/ZettaScript/typed-sled/tree/transaction-tuple) but I have some lifetime problem.

**Comment by chronicl** [comment]
That's a pretty neat feature of sled, I didn't know about it.  
I implemented an example for a 2-Tuple in a new [branch](https://github.com/chronicl/typed-sled/compare/main...transactional). Is this what you are looking for? If it is, I would continue implementing it properly for all tuples and document it.

**Comment by ZettaScript** [comment]
Yes it's exactly that! And your implementation is simpler than mine.

**Comment by chronicl** [comment]
I implemented it for all tuples with up to 11 entries and bumped the version to 0.2.3 which includes these changes.
